### ISSUE TITLE
Revisar Integracion

### ISSUE THREAD

**Issue by ErickFabian** [ErickFabian/Proyecto-Final-TSOA#3]
@LexMR Podrias revisar si no rompi tu parte con lo que integre? Y si me pudieras explicar mas o menos que hace tu practica estaria a todo dar por que no estoy muy seguro de como probar si esta funcionando bien.

**Comment by ghost** [comment]
Okas, voy a revisar.
Si me tardo en responder es por cuestiones de chamba, escuela y traslado, pero sí respondo.

Date: Tue, 19 May 2015 15:12:03 -0700
