### ISSUE TITLE
¿almacenamiento temporal implementado? 

### ISSUE THREAD

**Issue by SadisticFerras** [ErickFabian/Proyecto-Final-TSOA#4]
Antes que nada, quiero ofrecer disculpas por estar offline estos últimos días. 

Y con repecto al proyecto; ¿ya está implementado el almacenamiento temporal? no noto diferencia entre el comportamiento de la práctica 2 y lo que va del proyecto XD

Antes de implementar mis procesos y frames al proyecto, voy a integrar el código de mi práctica al micronucleo de Erick. Va a ser necesario tocar sus dos "ProcesoServidor" de forma similar a la que Erick modificó el de Alexander antes del while, un método al "Nucleo.java" y unas clases que son necesarias para mi práctica al paquete "modoMonitor". 

Otra cosa, necesito confirmación con respecto al funcionamiento del proyecto. Un cliente envía solicitud y es atendida, los siguientes tres entrarían en el buzón. Si llega una nueva solicitud y el servidor no ha terminado con el primer cliente (que siga el buzón lleno por ende) este pasa a almacenamiento temporal (en lugar de mandar Try Again, como mi práctica) durante 10 segundos. ¿Estoy en lo correcto? 

Y ya por último, si se le dificulta por el tiempo a Alexander integrar su almacenamiento temporal a mi práctica una vez que yo termine; rola tu práctica, me especificas lo básico y yo la integro (espero que fluya).

**Comment by SadisticFerras** [comment]
He terminado con esa parte. 

Ambos servidores y clientes parece que funcionan a la perfección con su buzón pero sin el Try again. Decidí crear un nuevo proyecto antes de hacer el commit en el proyecto de Erick. Verifiquen que funcione correctamente y después hacemos el commit.
https://github.com/SadisticFerras/Proyecto-Final-CONbuzones
No entiendo muy bien como funciona esto de los forks y tal XD. Ando perdidón en github.

En este momento paso a trabajar con la integración de mis dos procesos como de mis dos frames. Espero que fluya el cotorreo.

**Comment by ghost** [comment]
OKas, pues hazlo, para los tres tener uno solo funcionando internamente( los 3 con los 3) , dado que debe estar listo para mañana, para mandárselo al profe y saber si él nos detecta errores y poderlo modificar a tiempo.

**Comment by ErickFabian** [comment]
Ya lo revise y si parece funcionar  en seguida lo subo al repositorio principal para tener la referencia, faltaria mi parte de registrar tus servidores en mi DNS pero eso es realmente rapido no hay bronca, en cuanto tu subas tus frame yo hago eso y les aviso.

**Comment by SadisticFerras** [comment]
¿Para hoy? en la madre.

**Comment by SadisticFerras** [comment]
Actualicé el proyecto.
