### ISSUE TITLE
Implementacion Servidor de Nombres en Servidores y Clientes Completada

### ISSUE THREAD

**Issue by ErickFabian** [ErickFabian/Proyecto-Final-TSOA#5]
Ya termine la integracion de las ventanas de @SadisticFerras y @LexMR con el servidor de nombres
Creo que faltaria que revisaran la funcionalidad de sus practicas despues de la integracion, pero creo que de la parte de direccionamiento ya no hay colisiones, hay un asunto de hacer el servidor aleatorio de cada uno pero pues termina siendo trivial, si hay chance la implemento pero como sea ya funciona el servidor de nombres. Porfa revisen que este funcionando como debe si no para tambien yo pegarle a eso si ocupan.

**Comment by SadisticFerras** [comment]
Checando eso

**Comment by ghost** [comment]
Ok ahorita reviso
